name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Compose docker files
      run: docker compose build

  create_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create docker artifact, Clock
      run: DOCKER_BUILDKIT=1 docker image build -f ClockMqtt/Dockerfile --output type=tar,dest=clock.tar .

    - name: Create docker artifact, Display
      run: DOCKER_BUILDKIT=1 docker image build -f DisplayMqtt/Dockerfile --output type=tar,dest=display.tar .

    - name: Create docker artifact, Timer
      run: DOCKER_BUILDKIT=1 docker image build -f TimerMqtt/Dockerfile --output type=tar,dest=timer.tar .

  upload_artifacts:
    needs: create_artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Images
        path: ./*.tar

    - name: Upload a Build Artifact, Clock
      uses: actions/upload-artifact@v3
      with:
        name: ClockImage
        path: clock.tar

    - name: Upload a Build Artifact, Display
      uses: actions/upload-artifact@v3
      with:
        name: DisplayImage
        path: display.tar

    - name: Upload a Build Artifact, Timer
      uses: actions/upload-artifact@v3
      with:
        name: TimerImage
        path: timer.tar
