name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag binclock:$(date +%s) --output type=local,dest=out 

    - name: Compose docker files
      run: docker compose up

    - name: Save docker artifacts, Clock
      run: docker save -o clock.tar clock

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ClockImage
        path: clock.tar
